### ISSUE TITLE
RangeError: Stack Overflow when trying to run ts-node-dev in Chapter 3

### ISSUE THREAD

**Issue by TuhinNair** [async-labs/saas#103]
In Chapter 3, on running the updated yarn dev command for ts-node-dev the following error shows up.

![image](https://user-images.githubusercontent.com/59875893/91400014-2c42b200-e869-11ea-9d40-644a6f8e0d4a.png)

OS: Ubuntu 20.4

tsconfig.server.json
![image](https://user-images.githubusercontent.com/59875893/91400075-441a3600-e869-11ea-8f2a-4f947c133824.png)

server/server.ts
![image](https://user-images.githubusercontent.com/59875893/91400147-5dbb7d80-e869-11ea-94c5-41d54207bf94.png)

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #103</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/103.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by stavroslee** [comment]
I'm seeing the same issue with app/yarn dev

**Comment by tima101** [comment]
@TuhinNair @stavroslee Does `book/3-end/app` run as expected for you guys?

**Comment by tima101** [comment]
@TuhinNair @stavroslee Thank you for reporting. Seems like the problem is with versioning of `ts-node-dev` package.

Here are steps to fix:
- replace `--transpileOnly` with `--transpile-only`
- remove `ts-node-dev` package with `yarn remove ts-node-dev`; then install it with `yarn add ts-node-dev@1.0.0-pre.44 --dev` 

Make sure that there is no `^` in front of version of `ts-node-dev` inside `book/3-begin/app/package.json`

After running `yarn dev`, you should see these versions in your terminal:
```
Using ts-node version 9.0.0, typescript version 3.6.4
```

Please let me know if it resolves problem.

**Comment by stavroslee** [comment]
That resolved my issue! thank you

**Comment by TuhinNair** [comment]
@tima101 Thanks that solved the RangeError.

Note to folks using Linux+Node v14 you'll also need the `--poll` flag because of reasons discussed here https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform

**Comment by tima101** [comment]
@TuhinNair Thanks for additional info.

In the SaaS Boilerplate book, we ask to install Node 12.4.0 at the beginning of Chapter 1.

**Comment by TuhinNair** [comment]
Of course, that was just for people using the book as a guide and building something of their own alongside it.
