### ISSUE TITLE
store: [Circular] & stripeSubscription/isSubscriptionActive not updating in the store.

### ISSUE THREAD

**Issue by andrewshrout** [async-labs/saas#130]
**Expected Behavior**

When the subscription session ends, and the page is reloaded, I expect it to rerender, and I can now only cancel subscription.
I also expect that upon finishing my checkout session, my local store should update and not just my user in mongo.

**What actually happens**
StripeCard updates, stripeListofInvoices, and hasCardInformation updates. However, even if I log out, hit refresh, after checking out - it will not update my Billings page. Also store gets this infinite loop of [Circular]. Everything in the database however is correct!

```
MyApp.constructor
Store {
  isServer: true,
  currentUser: User {
    store: [Circular],
    _id: '5f6a387053ad584f0831254a',
    slug: 'andrew-shrout-1',
    email: '=====',
    displayName: 'Andrew Shrout',
    avatarUrl: 'https://lh4.googleusercontent.com/-H7jTmMGgT8s/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuclJFQc-Ly1AJ0eOR68PHJPylEWPJA/photo.jpg',
    isSignedupViaGoogle: true,
    darkTheme: false,
    stripeSubscription: undefined,
    isSubscriptionActive: undefined,
    isPaymentFailed: undefined,
    stripeCard: {
      brand: 'visa',
      country: 'US',
      exp_month: 1,
      exp_year: 2022,
      funding: 'credit',
      last4: '4242'
    },
    hasCardInformation: true,
    stripeListOfInvoices: { object: 'list', data: [Array], has_more: false 
}
  },
  currentUrl: '/billing'
```

**Other Context**
I've put all the TeamLeader stuff into user as there are no discussions or team leaders in my end product. I started from the "7-begin" and worked up until the Team stuff, and then implemented Stripe from chapter 9. I had originally attempted to "unwire" the end product in chapter 10 but it was ultimately too hard and embedded in the specific product you guys had built for me to understand. 

I've been tracing the API, writing it to be functional and reading all the documentation for 2 days now but I can't figure out why the store won't update. My assumption is its in _app or something to do with the props not updating. I would appreciate any help.

https://github.com/andrewshrout/saas-book-course/tree/master/book/7-begin

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #130</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/130.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by andrewshrout** [comment]
Are the values not observed by mobX because subscribeTeam would normally be a method for the Team class? If that's the case, would you just load stripe in the user class, call the fetchCheckoutSessionApi method -> and runInAction updating the user Store?

**Comment by tima101** [comment]
@andrewshrout I can look tomorrow at your code. A high level comment is that you removed `Team` data model and `Team` data store from your project but Stripe API infrastructure is integrated with both `Team` and `User`. In fact, `Billing` page's subscription status is per team, Team Leader purchases subscription per team:

https://github.com/async-labs/saas/blob/f5554cd10584b0130e56502c8d63961d75a7fc5f/api/server/models/Team.ts#L39
https://github.com/async-labs/saas/blob/f5554cd10584b0130e56502c8d63961d75a7fc5f/app/lib/store/team.ts#L47
https://github.com/async-labs/saas/blob/f5554cd10584b0130e56502c8d63961d75a7fc5f/app/pages/billing.tsx#L115

Does it help?

I briefly looked at your code and I see one problem, `publicFields` on `User` data model are missing a few Stripe-related properties:

https://github.com/andrewshrout/saas-book-course/blob/37940267d0451a253ca628e3898936e17b327dfd/book/7-begin/api/server/models/User.ts#L275

Meaning `API` server does not send this data to `APP` server or `APP` browser.

I recommend, if feasible, to deviate into your product at Chapter 10.

Let me know if you want me to run your project after fixing above problem but since you made a lot of changes to book's code I can't promise much.

PS Good job on getting this far in the book!

**Comment by tima101** [comment]
@andrewshrout I can look at code if you move your question into separate new issue but can't promise solution since this is outside of the book's scope. If you decide to create new issue, please rename this one and close it. Thanks.
