### ISSUE TITLE
NProgress example on 2-begin may be faulty

### ISSUE THREAD

**Issue by marcosCapistrano** [async-labs/saas#162]
I may be wrong but when NProgress get's rendered it:

-Hardly shows (css may be missing)
-Spinner does not show even though it's defaulted to be shown (doesn't show even if explicitly set to true)

Would also be nice to offer explanations on how to style it considering SSR, since it's a third-party library.
I ask that because my theory is that maybe it's not rendering correctly because it's styles are not being injected?

EDIT: For someone willing to test, just run 2-end and notice how NProgress is rendered (notice the lack of the spinner)

**Comment by klyburke** [comment]
@marcosCapistrano Thanks for reporting. Did you figure out the issue? I am happy to look into this.

**Comment by klyburke** [comment]
Hi @marcosCapistrano . I ran `2-end`, and you are right that the NProgress bar is hard to see. That is because `2-end` has the light theme enabled, and we were using an NProgress bar with a white background. The style for that NProgress bar is here: https://storage.googleapis.com/async-await/nprogress-light.min.css?v=1

In Chapter 2 (and subsequent chapters), we meant to use an NProgress bar with a dark gray background: https://storage.googleapis.com/async-await/nprogress-dark.min.css?v=1. 

The two background color options are introduced in Chapter 8, when we change the bar color based on a user's choice of light or dark theme.

I switched to the dark NProgress bar for Chapters 2-7. Thanks again for reporting!

---

Note that the design is a thin bar at the top of the screen, not a "spinner". Check out this web page that demonstrates how the bar works. Click the play button for `NProgress.start()` and then for `NProgress.done()`.

https://ricostacruz.com/nprogress/

**Comment by marcosCapistrano** [comment]
Oh i see! Im still early in the book so I was afraid that would be fixed on later chapters... So in chapter 8 we learn how to style it, that's awesome.
Also I mentioned the "spinner" because in https://ricostacruz.com/nprogress/ there is a spinner along with the progress bar on the top-right side. I tried enabling it on 2-begin and couldn't make it show up. That made me think the styles weren't being injected. But anyways, I will keep following on with the book.  Thanks for the reply!

**Comment by klyburke** [comment]
@marcosCapistrano  You're welcome!

Oh, I see what you mean by the spinner on https://ricostacruz.com/nprogress/. The NProgress bar in the book is only the thin bar at the top of the screen. No spinner.

If you pull the code that I pushed yesterday and then run `2-end`, you will see that the bar is now dark gray and much more visible.

**Comment by klyburke** [comment]
Thanks @marcosCapistrano ! I'll  test this out later.

**Comment by klyburke** [comment]
@marcosCapistrano Thanks again. I tried your version with spinner. Looks good! As @tima101 noted, we will push this in our November update: https://github.com/async-labs/saas/issues/163

**Comment by marcosCapistrano** [comment]
Awesome! Loving the book so far guys, great work!

**Comment by tima101** [comment]
Solved in #163
