### ISSUE TITLE
Cannot get past the /login screen

### ISSUE THREAD

**Issue by dejitaiza** [async-labs/saas#3]
Hello,

First of all, thank you a lot for this very promising boilerplate. I was just searching for something similar when I came across it on Hacker News.

I have tried to run it locally.

I did setup so far two MongoDB instances, Express session, Google oAuth secrets, and Mailchimp.

Upon trying to login, I am indeed redirected to the google login page. When I do login with Google, I am sent back to /create-team which immediately loads /login. Accessing /create-team directly also redirects me to /login. The user is however sent to my mailchimp list indeed.

Am I missing something obvious / doing something wrong?
Should I setup all the other providers (such as Amazon) for saas to work?

Thank you for your time.

**Comment by tima101** [comment]
@dejitaiza Hi, thank you for reporting. This may happen when `app` does not get `user` object from `api`.

Did you try demo app (https://saas-app.async-await.com/login)?
Demo app is up-to-date with public repo.

I am happy to debug, would you share your code in public repo?

I've noticed that our README file does not have these lines:
```
  SESSION_NAME="xxxxxx"
  SESSION_SECRET="xxxxxx"
```
https://github.com/expressjs/session#name
https://github.com/expressjs/session#secret

Please let me know if adding above two lines to your `.env` resolves problem.

Thanks.

**Comment by dejitaiza** [comment]
Hi @tima101 , and thank you very much for your answer!

It does indeed work brilliantly in your demo app.

I do have values set for Express' session name and secret. I also enabled Google+ API.

I also know that the authenticated user is returned after logging in, because I was able to catch it in passport's oauth2callback route, so I am assuming the error is happening after that. I got lost however in the stack when I tried to debug, as I'm not entirely familiar with it.

I also routinely encounter this error spewed by `yarn dev` in the `app` folder, but I am not sure if it's related as it happens even before I try to login (no logs from the `api` process to correlate with this error).

```
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 404.
<p>Message: File not found.
<p>Error code explanation: 404 = Nothing matches the given URI.
</body>

Error: File not found
    at Object.sendRequestAndGetResponse [as default] (path/to/repo/app/lib/api/sendRequestAndGetResponse.ts:35:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

I tried the master branch, as well as the releases v1.1.0, v1.0.1 and some older ones to no avail, so I am really suspecting that my configuration is incorrect.

In the Readme.md file, some `.env` variables are mentioned as being required while some others are optional. This is unfortunately not detailed afterwards.

The only two services I did not setup are Amazon and Stripe. Could it be this?

If this is not the case, could you pinpoint me to the best location where I could start the debugging? (i.e. where the redirection to /create-team happens exactly).

**Comment by tima101** [comment]
@dejitaiza Thanks a lot for very detailed description. I added this line to `.env` description inside README: https://github.com/async-labs/saas/commit/9900b9c5a192b8bd3778f7008c737bfea6d1d216

Please check up this code block:
```
      try {
        await sendEmail({
          from: `Kelly from async-await.com <${process.env.EMAIL_SUPPORT_FROM_ADDRESS}>`,
          to: [email],
          subject: template.subject,
          body: template.message,
        });
      } catch (err) {
        logger.error('Email sending error:', err);
      }
```

Please make sure you have following in your `.env` file:
```
  # Used in api/server/aws-s3.ts and api/server/aws-ses.ts
  Amazon_accessKeyId="xxxxxx"
  Amazon_secretAccessKey="xxxxxx"

  # Used in api/server/models/Invitation.ts and api/server/models/User.ts
  EMAIL_SUPPORT_FROM_ADDRESS="xxxxxx"
```

But you are also welcome to comment out this block of code, you can add transactional emails feature later on. (Tslint will probably ask you to remove unnecessary imports and etc.)

Let me know if this helps. Thanks.

**Comment by dejitaiza** [comment]
I setup Amazon now, and filled `EMAIL_SUPPORT_FROM_ADDRESS` as well in `.env`.
It didn't solve the problem, unfortunately.

The code block you linked to seems to never execute after some console logs (no transactional email was sent).
I'm going to debug this more in-depth now (also an opportunity to get familiar with `saas` as well 😄).

I will keep you posted with my findings.
Thank you for your help so far.

**Comment by dejitaiza** [comment]
Interestingly enough, while trying to setup a debugging configuration for vscode, I changed the ts target to `es6`, and the module system to `commonjs`.

The frontend then magically started working, and after logging in again this time I was presented with the `/create-team`.

This workaround is good enough for me. I am fine closing this ticket on my end.

**Comment by tima101** [comment]
@dejitaiza I would guess that it was related to config of AWS SES. 

Ok, closed.

**Comment by dejitaiza** [comment]
Just for reference, configuring AWS SES didn't change anything. It's only when I switch the target to `es6` that it worked. It also doesn't work anymore if I switch back to `esnext`.

**Comment by tima101** [comment]
@dejitaiza Thanks for replying. I think this config problem deserves more testing. I would like to reproduce/solve this config problem in case someone else gets stuck because of it.

You are talking about config inside app/tsconfig.json?

Would you please share your settings for workspace and user inside your VS editor?
Would you share code in public repo as well?

**Comment by tima101** [comment]
@dejitaiza 

> while trying to setup a debugging configuration for vscode, I changed the ts target to `es6`, and the module system to `commonjs`

- What were the values before you changed them?
- Did you make above changes inside `tsconfig.json` or somewhere on VS code editor?

Thanks.

**Comment by Moai-** [comment]
I am also experiencing this issue. The above solution of setting module and target did not work for me.

Both app and api are on two separate docker instances, and both appear to be working fine. Database is populating OK. When I try to log in through Google, I can see that a) the API gets the request, b) user gets saved to the database, c) the browser is redirected to `create-team`. However, as soon as it hits `create-team`, it goes back to the login screen.  

I have traced this down to my version of the app not setting a cookie upon returning from the google oauth login screen. I have the `SESSION_SECRET` and `SESSION_NAME` matching on both api and  app ENV vars. COOKIE_DOMAIN is set to `herokuapp.com`, app is running on `myapp.herokuapp.com` (example), and api is on `myapi.herokuapp.com`. I can see that in your live version of the app, a cookie is created for the domain. In my version, the cookie never gets set, and, I assume because of that, the user never gets populated into the app store.  

@tima101 Could you tell me by which method the app store gets the user information? Also, can you think of any reason why my cookies would not be setting, but yours are? Tested in both Chrome and Firefox.

**Comment by Moai-** [comment]
Figured I'd comment again because I figured out the problem. According to this (https://devcenter.heroku.com/articles/cookies-and-herokuapp-com), herokuapp.com is not a valid cookie domain. I have moved my app to custom domains, and now login functionality works.
