### ISSUE TITLE
Does it create databse per user or it keeps One database where users are separated at logical level

### ISSUE THREAD

**Issue by kunalahirrao** [async-labs/saas#81]
<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #81</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/81.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@kunalahirrao For each signed up user there is a corresponding user MongoDB document inside `users` collection of MongoDB database. `API` server connects to one MongoDB database. `APP` browser or server (depending on client- or server-side rendering) communicates with `API` server.

If you meant to ask about `Team` instead of `User`. The answer is the same, multiple team documents, in `team` collection of one database. Logically separated by `teamId`.

**Comment by kunalahirrao** [comment]
Now it's crystal clear that it separates teams at logical level
